/* Generated by Cython 0.29.34 */

#ifndef __PYX_HAVE__pyplanes
#define __PYX_HAVE__pyplanes

#include "Python.h"

#ifndef __PYX_HAVE_API__pyplanes

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C void pyplane(int, int, int, double *, double *, int);
__PYX_EXTERN_C void pyplane27(int, int, int, double *, double *, int);
__PYX_EXTERN_C void pyplane_xz(int, int, int, double *, double *, int);
__PYX_EXTERN_C void pyplane_xz27(int, int, int, double *, double *, int);
__PYX_EXTERN_C void pyplane_yz(int, int, int, double *, double *, int);
__PYX_EXTERN_C void pyplane_yz27(int, int, int, double *, double *, int);

#endif /* !__PYX_HAVE_API__pyplanes */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initpyplanes(void);
#else
PyMODINIT_FUNC PyInit_pyplanes(void);
#endif

#endif /* !__PYX_HAVE__pyplanes */
