! ==========================================================================
! 
! 
!    "f90/f95" include file generated by $BOXMGdist/make/BMGincludes.py
! 
! 
      INTEGER    iZERO, iONE, iTWO, iTHREE, iFOUR, iFIVE,                  &
                 iSIX, iSEVEN, iEIGHT, iNINE, iTEN

      PARAMETER( iZERO = 0, iONE = 1, iTWO  = 2, iTHREE = 3,               &
                  iFOUR = 4, iFIVE = 5, iSIX = 6, iSEVEN = 7,              &
                  iEIGHT = 8, iNINE = 9, iTEN = 10             )

      REAL(8)     rZERO, rONE, rTWO, rTHREE, rFOUR, rFIVE,                 &
                 rSIX, rSEVEN, rEIGHT, rNINE, rTEN

      PARAMETER( rZERO = 0, rONE = 1, rTWO = 2, rTHREE = 3,                &
                 rFOUR = 4, rFIVE = 5, rSIX = 6, rSEVEN = 7,               &
                 rEIGHT = 8, rNINE = 9, rTEN = 10              )

