/*

     "C" include file generated by $BOXMGdist/make/BMGincludes.py

*/


#ifndef _BMG_parameters_h
#define _BMG_parameters_h

/*========================================================================== */
/*--------------------                                                       */
/*DESCRIPTION:                                                               */
/*--------------------                                                       */
/*                                                                           */
/*This include file provides a single resource for defining commonly         */
/*used parameters in the BOXMG family of codes.                              */
/*                                                                           */
/*=======================================================================    */
/*$license_flag$                                                             */
/*=======================================================================    */
/*--------------------                                                       */
/*VARIABLES:                                                                 */
/*--------------------                                                       */
/*                                                                           */
/*                                                                           */
/*========================================================================== */
/*----------------------------------------------------                       */
/*Parameter Indexing                                                         */
/*---------------------------------                                          */

/*---------------------------------                                          */
/*INTEGER Parameters                                                         */
/*---------------------------------                                          */

#define id_BMG2_DIM_NOG                   0
#define id_BMG2_DIM_NF                    1
#define id_BMG2_DIM_NC                    2
#define id_BMG2_DIM_NSO                   3
#define id_BMG2_DIM_NSOR                  4
#define id_BMG2_DIM_NCI                   5
#define id_BMG2_DIM_NCBW                  6
#define id_BMG2_DIM_NCU                   7
#define id_BMG2_DIM_Nx                    8
#define id_BMG2_DIM_Ny                    9
#define id_BMG2_DIM_NBASIS                10
#define id_BMG2_DIM_NDT                   11
#define id_BMG2_DIM_NHOT                  12
#define id_BMG2_POINTERS                  13
#define id_BMG2_STENCIL                   14
#define id_BMG2_BC                        15
#define id_BMG2_SETUP                     16
#define id_BMG2_INITIAL_Q                 17
#define id_BMG2_RELAX                     18
#define id_BMG2_RELAX_SYM                 19
#define id_BMG2_NRELAX_DOWN               20
#define id_BMG2_NRELAX_UP                 21
#define id_BMG2_NRELAX_FG                 22
#define id_BMG2_CYCLE_CLASS               23
#define id_BMG2_NCYCLE_TYPE               24
#define id_BMG2_FMG_NNCYCLE               25
#define id_BMG2_MAX_ITERS                 26
#define id_BMG2_STOP_TEST                 27
#define id_BMG2_MIN_NOG                   28
#define id_BMG2_CG_MIN_DIM                29
#define id_BMG2_CG_CONSTRUCT              30
#define id_BMG2_CG_TYPE                   31
#define id_BMG2_Err_Code                  32
#define id_BMG2_Ext_Err_Code              33
#define id_BMG2_OUT_ITERS                 34
#define id_BMG2_OUTFILE_UNIT              35
#define id_BMG2_DEBUG_LEVEL               36
#define id_BMG2_DIAG_coefs                37
#define id_BMG2_DIAG_basis                38
#define id_BMG3_DIM_NOG                   39
#define id_BMG3_DIM_NF                    40
#define id_BMG3_DIM_NC                    41
#define id_BMG3_DIM_NSO                   42
#define id_BMG3_DIM_NSOR                  43
#define id_BMG3_DIM_NCI                   44
#define id_BMG3_DIM_NCBW                  45
#define id_BMG3_DIM_NCU                   46
#define id_BMG3_DIM_NSO3                  47
#define id_BMG3_DIM_NSR3                  48
#define id_BMG3_DIM_NCI3                  49
#define id_BMG3_DIM_NCPL                  50
#define id_BMG3_DIM_Nx                    51
#define id_BMG3_DIM_Ny                    52
#define id_BMG3_DIM_Nz                    53
#define id_BMG3_DIM_NBASIS                54
#define id_BMG3_DIM_NDT                   55
#define id_BMG3_DIM_NHOT                  56
#define id_BMG3_POINTERS                  57
#define id_BMG3_STENCIL                   58
#define id_BMG3_BC                        59
#define id_BMG3_SETUP                     60
#define id_BMG3_INITIAL_Q                 61
#define id_BMG3_RELAX                     62
#define id_BMG3_RELAX_SYM                 63
#define id_BMG3_NRELAX_DOWN               64
#define id_BMG3_NRELAX_UP                 65
#define id_BMG3_NRELAX_FG                 66
#define id_BMG3_CYCLE_CLASS               67
#define id_BMG3_NCYCLE_TYPE               68
#define id_BMG3_FMG_NNCYCLE               69
#define id_BMG3_MAX_ITERS                 70
#define id_BMG3_STOP_TEST                 71
#define id_BMG3_MIN_NOG                   72
#define id_BMG3_CG_MIN_DIM                73
#define id_BMG3_CG_TYPE                   74
#define id_BMG3_CG_CONSTRUCT              75
#define id_BMG3_Err_Code                  76
#define id_BMG3_Ext_Err_Code              77
#define id_BMG3_OUT_ITERS                 78
#define id_BMG3_OUTFILE_UNIT              79
#define id_BMG3_DEBUG_LEVEL               80
#define id_BMG3_DIAG_coefs                81
#define id_BMG3_DIAG_basis                82
#define id_BMG2_xy                        83
#define id_BMG2_xz                        84
#define id_BMG2_yz                        85
#define NBMG2_iPARMS                      42
#define NBMG3_iPARMS                      44
#define NBMG_iPARMS                       86

/*-------------------------------                                            */
/*REAL Parameters                                                            */
/*-------------------------------                                            */

#define id_BMG2_STOP_TOL                  0
#define id_BMG2_OUT_TOL                   1
#define id_BMG2_OUT_RHO_init              2
#define id_BMG2_OUT_RHO_last              3
#define id_BMG2_OUT_RHO_avg               4
#define id_BMG2_TIME_SETUP                5
#define id_BMG2_TIME_SETUP_CG_ITLI        6
#define id_BMG2_TIME_SETUP_INTERP_OI      7
#define id_BMG2_TIME_SETUP_RELAX          8
#define id_BMG2_TIME_SETUP_CG_LU          9
#define id_BMG2_TIME_SETUP_PTR_GRID       10
#define id_BMG2_TIME_SETUP_PARTS          11
#define id_BMG2_TIME_CYCLE                12
#define id_BMG2_TIME_relax                13
#define id_BMG2_TIME_restrict             14
#define id_BMG2_TIME_interp_add           15
#define id_BMG2_TIME_SOLVE_CG             16
#define id_BMG2_TIME_PCG_PRECON           17
#define id_BMG2_TIME_PCG_TOTAL            18
#define id_BMG2_TIME_TOTAL                19
#define id_BMG3_STOP_TOL                  20
#define id_BMG3_OUT_TOL                   21
#define id_BMG3_OUT_RHO_init              22
#define id_BMG3_OUT_RHO_last              23
#define id_BMG3_OUT_RHO_avg               24
#define id_BMG3_TIME_SETUP                25
#define id_BMG3_TIME_SETUP_CG_ITLI        26
#define id_BMG3_TIME_SETUP_INTERP_OI      27
#define id_BMG3_TIME_SETUP_RELAX          28
#define id_BMG3_TIME_SETUP_CG_LU          29
#define id_BMG3_TIME_SETUP_PTR_GRID       30
#define id_BMG3_TIME_SETUP_PARTS          31
#define id_BMG3_TIME_CYCLE                32
#define id_BMG3_TIME_relax                33
#define id_BMG3_TIME_restrict             34
#define id_BMG3_TIME_interp_add           35
#define id_BMG3_TIME_SOLVE_CG             36
#define id_BMG3_TIME_PCG_PRECON           37
#define id_BMG3_TIME_PCG_TOTAL            38
#define id_BMG3_TIME_TOTAL                39
#define NBMG2_rPARMS                      20
#define NBMG3_rPARMS                      20
#define NBMG_rPARMS                       40

/*----------------------------------------------------                       */
/*========================================================================== */
/*----------------------------------------------------                       */
/*Parameter Values                                                           */
/*-------------------------------                                            */

/*-------------------------------                                            */
/*Stencil Type                                                               */
/*-------------------------------                                            */

#define BMG_STENCIL_5pt                   1
#define BMG_STENCIL_9pt                   2
#define BMG_STENCIL_7pt                   1
#define BMG_STENCIL_27pt                  2

/*-------------------------------                                            */
/*Periodicity                                                                */
/*-------------------------------                                            */

#define BMG_BCs_definite                  0
#define BMG_BCs_def_per_x                 2
#define BMG_BCs_def_per_y                 1
#define BMG_BCs_def_per_xy                3
#define BMG_BCs_indef_per_x               -2
#define BMG_BCs_indef_per_y               -1
#define BMG_BCs_indef_per_xy              -3
#define BMG_BCs_indef_nonper              -4
#define BMG_BCs_def_per_z                 5
#define BMG_BCs_def_per_xz                6
#define BMG_BCs_def_per_yz                7
#define BMG_BCs_def_per_xyz               8
#define BMG_BCs_indef_per_z               -5
#define BMG_BCs_indef_per_xz              -6
#define BMG_BCs_indef_per_yz              -7
#define BMG_BCs_indef_per_xyz             -8

/*-------------------------------                                            */
/*Setup options:                                                             */
/*-------------------------------                                            */

#define BMG_SETUP_only                    3
#define BMG_SETUP_none                    2
#define BMG_SETUP_opers                   1
#define BMG_SETUP_ptrs_opers              0

/*-------------------------------                                            */
/*Memory Allocation:                                                         */
/*-------------------------------                                            */

#define BMG_USE_pointers                  1
#define BMG_NO_pointers                   0

/*-------------------------------                                            */
/*Relaxation:                                                                */
/*-------------------------------                                            */

#define BMG_GS_RB_point                   1
#define BMG_GS_RB_x_lines                 2
#define BMG_GS_RB_y_lines                 3
#define BMG_GS_RB_x_y_lines               4
#define BMG_GS_RB_planes_xy_yz_xz         5

/*--------------------------------                                           */
/*Symmetry of the MG n-cycle:                                                */
/*--------------------------------                                           */

#define BMG_RELAX_NONSYM                  0
#define BMG_RELAX_SYM                     1

#define BMG_DOWN                          0
#define BMG_UP                            1

/*--------------------------------                                           */
/*Initial Guess                                                              */
/*--------------------------------                                           */

#define BMG_GUESS_ZERO                    0
#define BMG_GUESS_RANDOM                  1
#define BMG_GUESS_USER                    2
#define BMG_GUESS_USER_GHOST              3

/*--------------------------------                                           */
/*Stopping Criteria                                                          */
/*--------------------------------                                           */

#define BMG_STOP_ABS_RES_L2               0
#define BMG_STOP_REL_RES_L2               1
#define BMG_STOP_MAX_ITERS                2

/*--------------------------------                                           */
/*Cycle Class and Type                                                       */
/*--------------------------------                                           */

#define BMG_FMG_CYCLE                     0
#define BMG_N_CYCLE                       1
#define BMG_V_CYCLE                       1
#define BMG_W_CYCLE                       2

/*--------------------------------                                           */
/*Coarse-Grid Operator Type                                                  */
/*--------------------------------                                           */

#define BMG_CG_ITLI_IzIyIx                1
#define BMG_CG_ITLI                       2
#define BMG_CG_USER                       3

/*--------------------------------                                           */
/*I^{T} L I Construction                                                     */
/*--------------------------------                                           */

#define BMG_CG_CONS_explicit              1
#define BMG_CG_CONS_block                 2

/*--------------------------------                                           */
/*Output and Debugging                                                       */
/*--------------------------------                                           */

#define BMG_UNIT_STDOUT                   6
#define BMG_UNIT_DUMP                     10
#define BMG_UNIT_BUGOUT                   42

#define BMG_DEBUG_NONE                    1
#define BMG_DEBUG_MEMORY                  2
#define BMG_DEBUG_ITERATIONS              3
#define BMG_DEBUG_RESIDUALS               4
#define BMG_DEBUG_OPERATORS               5

/*--------------------------------                                           */
/*Diagnostics                                                                */
/*--------------------------------                                           */

#define BMG_DIAG_COEFS_NONE               1
#define BMG_DIAG_COEFS_ALL                2
#define BMG_DIAG_COEFS_CG                 3

#define BMG_DIAG_BASIS_NONE               1
#define BMG_DIAG_BASIS_ONE                2

/*----------------------------------------------------                       */
/*========================================================================== */
/*----------------------------------------------------                       */
/*IOFLAG Indexing                                                            */
/*---------------------------------                                          */

#define iBMG2_BUG_STENCIL_FG              0
#define iBMG2_BUG_STENCIL_CG              1
#define iBMG2_BUG_STENCIL_CG1             2
#define iBMG2_BUG_RESTRICT                3
#define iBMG2_BUG_INTERP                  4
#define iBMG2_BUG_RES_INTERP              5
#define iBMG2_BUG_RES_RESTRICT            6
#define iBMG2_BUG_RES_RELAX               7
#define iBMG2_BUG_RES_CG_SOLVE            8
#define iBMG2_BUG_S                       9
#define iBMG2_BUG_CSC_STENCIL             10
#define iBMG2_BUG_CSC_BOUNDARY            11
#define iBMG2_OUT_WSPACE_SIZE             12
#define iBMG2_OUT_WSPACE_POINT            13
#define iBMG2_OUT_TIME_SETUP              14
#define iBMG2_OUT_TIME_CYCLING            15
#define iBMG2_OUT_TIME_TOTAL              16
#define iBMG2_OUT_ITERATIONS              17
#define iBMG2_OUT_STENCIL_TTY             18
#define iBMG2_OUT_RESTRICT_TTY            19
#define iBMG2_OUT_INTERP_TTY              20
#define iBMG2_WARN_ZERO_RESIDUAL          21
#define iBMG2_OUT_STOP_ERROR              22
#define iBMG3_BUG_STENCIL_FG              23
#define iBMG3_BUG_STENCIL_CG              24
#define iBMG3_BUG_STENCIL_CG1             25
#define iBMG3_BUG_RESTRICT                26
#define iBMG3_BUG_INTERP                  27
#define iBMG3_BUG_RES_INTERP              28
#define iBMG3_BUG_RES_RESTRICT            29
#define iBMG3_BUG_RES_RELAX               30
#define iBMG3_BUG_RES_CG_SOLVE            31
#define iBMG3_BUG_S                       32
#define iBMG3_BUG_CSC_STENCIL             33
#define iBMG3_BUG_CSC_BOUNDARY            34
#define iBMG3_OUT_WSPACE_SIZE             35
#define iBMG3_OUT_WSPACE_POINT            36
#define iBMG3_OUT_TIME_SETUP              37
#define iBMG3_OUT_TIME_CYCLING            38
#define iBMG3_OUT_TIME_TOTAL              39
#define iBMG3_OUT_ITERATIONS              40
#define iBMG3_OUT_STENCIL_TTY             41
#define iBMG3_OUT_RESTRICT_TTY            42
#define iBMG3_OUT_INTERP_TTY              43
#define iBMG3_WARN_ZERO_RESIDUAL          44
#define iBMG3_OUT_STOP_ERROR              45
#define iBMG_OUT_SOLUTION                 46
#define iBMG_OUT_RHS                      47
#define NBMG2_IOFLAG                      23
#define NBMG3_IOFLAG                      23
#define NBMG_IOFLAG                       48

/*----------------------------------------------------                       */
/*========================================================================== */


#endif

