/*

     "C" include file generated by $BOXMGdist/make/BMGincludes.py

*/


#ifndef BMG_workspace_h
#define BMG_workspace_h

#define ip_U                              0
#define ip_Q                              1
#define ip_RES                            2
#define ip_SO                             3
#define ip_SOR                            4
#define ip_CI                             5
#define ip_CU                             6
#define ip_CSO                            7
#define ip_hG                             8
#define ip_iG                             9
#define ip_BMG_PCG_P                      10
#define ip_BMG_PCG_R                      11
#define ip_BMG_PCG_Z                      12

#define ip_MSG                            13
#define ip_MSGSO                          14
#define ip_MSG_BUF                        15
#define ip_ProcGrid                       16
#define ip_LS                             17

#define NBMG_pWORK                        18

#define ip_BMG_iPARMS_PL_xy               0
#define ip_BMG_iPARMS_PL_yz               1
#define ip_BMG_iPARMS_PL_xz               2
#define ip_BMG_pWORK_PL_xy                3
#define ip_BMG_pWORK_PL_yz                4
#define ip_BMG_pWORK_PL_xz                5
#define ip_BMG_iWORK_pSI_xy               6
#define ip_BMG_iWORK_pSI_yz               7
#define ip_BMG_iWORK_pSI_xz               8
#define ip_BMG_iWORK_pSR_xy               9
#define ip_BMG_iWORK_pSR_yz               10
#define ip_BMG_iWORK_pSR_xz               11
#define ip_BMG_iWORK_PL_SF                12
#define ip_BMG_rWORK_PL_SF                13
#define ip_BMG_CGTEMP_yo                  14
#define ip_BMG_CGTEMP_zo                  15

#define NBMG_iWORK_PL_ptrs                16

#define id_BMG_iWORK_CS_NCBW              0
#define id_BMG_iWORK_CS_NCU               1
#define id_BMG_NOGm_CS                    2
#define id_BMG_iWORK_CS                   3
#define id_BMG_rWORK_CS                   4
#define id_BMG_iWORK_PL_CS                5
#define id_BMG_rWORK_PL_CS                6
#define ip_BMG_iWORK_CS_CSO               7
#define ip_BMG_iWORK_CS_CU                8
#define ip_BMG_iPARMS_CS                  9
#define ip_BMG_rPARMS_CS                  10
#define ip_BMG_pWORK_CS                   11
#define ip_BMG_iWORK_CS                   12
#define ip_BMG_rWORK_CS                   13
#define ip_BMG_iWORK_PL_CS                14
#define ip_BMG_rWORK_PL_CS                15
#define ip_BMG_iWORK_CS_SF                16
#define ip_BMG_rWORK_CS_SF                17

#define NBMG_iWORK_CS_ptrs                18

#define i_InWORK_SO                       0
#define i_InWORK_U                        1
#define i_InWORK_Q                        2
#define i_InWORK_RES                      3
#define i_InWORK_PCG_P                    4
#define i_InWORK_PCG_R                    5
#define i_InWORK_PCG_Z                    6

#define NBMG_InWORK                       7

#define ipL_BMG_U                         1
#define ipL_BMG_SO                        2
#define ipL_BMG_SOR                       3
#define ipL_BMG_CI                        4

#define idL_BMG_IVW                       5
#define idL_BMG_NLx                       6
#define idL_BMG_NLy                       7
#define idL_BMG_NLz                       8
#define idL_BMG_NGx                       9
#define idL_BMG_NGy                       10
#define idL_BMG_NGz                       11
#define idL_BMG_Icoord                    12
#define idL_BMG_Jcoord                    13
#define idL_BMG_Kcoord                    14

#define NBMG_pIGRD                        14

#define ipL_MSG_Index                     0
#define ipL_MSG_LocalArraySize            1
#define ipL_MSG_Proc                      2
#define ipL_MSG_Ipr                       3
#define ipL_MSG_NumAdjProc                4
#define ipL_MSG_ActDataStart              5
#define ipL_MSG_GlobalCoordLocalData      6
#define ipL_MSG_GlobalCoordActData        7
#define ipL_MSG_ProcGrid                  8
#define ipL_MSG_ProcGridCoord_x           9
#define ipL_MSG_ProcGridCoord_y           10
#define ipL_MSG_ProcGridCoord_z           11

#define NBMG_pMSG                         12

#define ipL_LS_XDataDist                  0
#define ipL_LS_YDataDist                  1
#define ipL_LS_ZDataDist                  2

#define NBMG_pLS                          3

#define ip_BMG_MSG_iWORK_pLS              0
#define ip_BMG_MSG_iWORK_pU               1
#define ip_BMG_MSG_iWORK_pSO              2
#define ip_BMG_MSG_iWORK_pyo              3
#define ip_BMG_MSG_iWORK_pzo              4
#define ip_BMG_MSG_iWORK_LS               5
#define ip_BMG_MSG_iWORK_U                6
#define ip_BMG_MSG_iWORK_SO               7
#define ip_BMG_MSG_iWORK_yo               8
#define ip_BMG_MSG_iWORK_zo               9

#define NBMG_MSG_pWORK                    10

#define id_BMG_MSG_NGx                    0
#define id_BMG_MSG_NGy                    1
#define id_BMG_MSG_NGz                    2
#define id_BMG_MSG_NLx                    3
#define id_BMG_MSG_NLy                    4
#define id_BMG_MSG_NLz                    5
#define id_BMG_MSG_iGs                    6
#define id_BMG_MSG_jGs                    7
#define id_BMG_MSG_kGs                    8
#define id_BMG_MSG_NProc                  9
#define id_BMG_MSG_NProcI                 10
#define id_BMG_MSG_NProcJ                 11
#define id_BMG_MSG_NProcK                 12
#define id_BMG_MSG_MyProc                 13
#define id_BMG_MSG_MyProcI                14
#define id_BMG_MSG_MyProcJ                15
#define id_BMG_MSG_MyProcK                16
#define id_BMG_MSG_COMM                   17
#define id_BMG_MSG_COMM_x                 18
#define id_BMG_MSG_COMM_y                 19
#define id_BMG_MSG_COMM_xy                20
#define id_BMG_MSG_COMM_yz                21
#define id_BMG_MSG_COMM_xz                22

#define NBMG_MSG_iGRID_data               23

#define ip_BMG_MSG_NLx_Grid               0
#define ip_BMG_MSG_NLy_Grid               1
#define ip_BMG_MSG_NLz_Grid               2
#define ip_BMG_MSG_iGs_Grid               3
#define ip_BMG_MSG_jGs_Grid               4
#define ip_BMG_MSG_kGs_Grid               5
#define ip_BMG_MSG_ProcGrid               6
#define ip_BMG_MSG_ProcCoord              7

#define NBMG_MSG_pGRID                    8

#define BMG_MSG_GRIDDIST_UNIFORM          1
#define BMG_MSG_GRIDDIST_CUSTOM           2
#define BMG_MSG_GRIDDIST_AUTOMATIC        3

#define MaxNumProc                        99

#define ipL_PGrid                         0
#define ipL_NProcI                        1
#define ipL_NProcJ                        2
#define ipL_NProcK                        3
#define ipL_MyProcI                       4
#define ipL_MyProcJ                       5
#define ipL_MyProcK                       6

#define NBMG_ProcGridInfo                 7


#endif

