/*

     "C" include file generated by $BOXMGdist/make/BMGincludes.py

*/


#ifndef BMG_parameters_h
#define BMG_parameters_h

#define id_BMG2_DIM_NOG                   0
#define id_BMG2_DIM_NF                    1
#define id_BMG2_DIM_NC                    2
#define id_BMG2_DIM_NSO                   3
#define id_BMG2_DIM_NSOR                  4
#define id_BMG2_DIM_NCI                   5
#define id_BMG2_DIM_NCBW                  6
#define id_BMG2_DIM_NCU                   7
#define id_BMG2_DIM_NMSGi                 8
#define id_BMG2_DIM_NMSGr                 9
#define id_BMG2_POINTERS                  10
#define id_BMG2_STENCIL                   11
#define id_BMG2_BC                        12
#define id_BMG2_SETUP                     13
#define id_BMG2_INITIAL_Q                 14
#define id_BMG2_RELAX                     15
#define id_BMG2_RELAX_SYM                 16
#define id_BMG2_NRELAX_DOWN               17
#define id_BMG2_NRELAX_UP                 18
#define id_BMG2_NRELAX_FG                 19
#define id_BMG2_CYCLE_CLASS               20
#define id_BMG2_NCYCLE_TYPE               21
#define id_BMG2_FMG_NNCYCLE               22
#define id_BMG2_MIN_ITERS                 23
#define id_BMG2_MAX_ITERS                 24
#define id_BMG2_STOP_TEST                 25
#define id_BMG2_MIN_NOG                   26
#define id_BMG2_CG_MIN_DIM                27
#define id_BMG2_CG_TYPE                   28
#define id_BMG2_CG_CONSTRUCT              29
#define id_BMG2_CG_COMM                   30
#define id_BMG2_CG_SOLVER                 31
#define id_BMG2_SYNC_INITIAL_GUESS        32
#define id_BMG2_LINE_SOLVE_COMM_TYPE      33
#define id_BMG2_SETUP_MSG                 34
#define id_BMG2_Err_Code                  35
#define id_BMG2_Ext_Err_Code              36
#define id_BMG2_OUT_ITERS                 37
#define id_BMG2_OUTFILE_UNIT              38
#define id_BMG2_DEBUG_LEVEL               39
#define id_BMG3_DIM_NOG                   40
#define id_BMG3_DIM_NF                    41
#define id_BMG3_DIM_NC                    42
#define id_BMG3_DIM_NSO                   43
#define id_BMG3_DIM_NSOR                  44
#define id_BMG3_DIM_NCI                   45
#define id_BMG3_DIM_NCBW                  46
#define id_BMG3_DIM_NCU                   47
#define id_BMG3_DIM_NMSGi                 48
#define id_BMG3_DIM_NMSGr                 49
#define id_BMG3_DIM_NSO3                  50
#define id_BMG3_DIM_NSR3                  51
#define id_BMG3_DIM_NCI3                  52
#define id_BMG3_DIM_NCPL                  53
#define id_BMG3_POINTERS                  54
#define id_BMG3_STENCIL                   55
#define id_BMG3_BC                        56
#define id_BMG3_SETUP                     57
#define id_BMG3_INITIAL_Q                 58
#define id_BMG3_RELAX                     59
#define id_BMG3_RELAX_SYM                 60
#define id_BMG3_NRELAX_DOWN               61
#define id_BMG3_NRELAX_UP                 62
#define id_BMG3_NRELAX_FG                 63
#define id_BMG3_CYCLE_CLASS               64
#define id_BMG3_NCYCLE_TYPE               65
#define id_BMG3_FMG_NNCYCLE               66
#define id_BMG3_MIN_ITERS                 67
#define id_BMG3_MAX_ITERS                 68
#define id_BMG3_STOP_TEST                 69
#define id_BMG3_MIN_NOG                   70
#define id_BMG3_CG_MIN_DIM                71
#define id_BMG3_CG_TYPE                   72
#define id_BMG3_CG_CONSTRUCT              73
#define id_BMG3_CG_COMM                   74
#define id_BMG3_CG_SOLVER                 75
#define id_BMG3_SYNC_INITIAL_GUESS        76
#define id_BMG3_Err_Code                  77
#define id_BMG3_Ext_Err_Code              78
#define id_BMG3_OUT_ITERS                 79
#define id_BMG3_OUTFILE_UNIT              80
#define id_BMG3_DEBUG_LEVEL               81
#define NBMG2_iPARMS                      40
#define NBMG3_iPARMS                      42
#define NBMG_iPARMS                       82

#define id_BMG2_STOP_TOL                  0
#define id_BMG2_OUT_TOL                   1
#define id_BMG2_OUT_RES_L2_0              2
#define id_BMG2_OUT_RES_L2_final          3
#define id_BMG2_OUT_RHO_init              4
#define id_BMG2_OUT_RHO_last              5
#define id_BMG2_OUT_RHO_avg               6
#define id_BMG2_TIME_SETUP                7
#define id_BMG2_TIME_SETUP_FINE_STENCIL   8
#define id_BMG2_TIME_SETUP_CG_ITLI        9
#define id_BMG2_TIME_SETUP_INTERP_OI      10
#define id_BMG2_TIME_SETUP_RELAX          11
#define id_BMG2_TIME_SETUP_CG_LU          12
#define id_BMG2_TIME_SETUP_PTR_GRID       13
#define id_BMG2_TIME_SETUP_PARTS          14
#define id_BMG2_TIME_SETUP_MSG            15
#define id_BMG2_TIME_SETUP_LS             16
#define id_BMG2_TIME_SETUP_TOTAL          17
#define id_BMG2_TIME_CYCLE                18
#define id_BMG2_TIME_relax                19
#define id_BMG2_TIME_restrict             20
#define id_BMG2_TIME_interp_add           21
#define id_BMG2_TIME_SOLVE_CG             22
#define id_BMG2_TIME_SOLVE_TOTAL          23
#define id_BMG2_TIME_PCG_TOTAL            24
#define id_BMG2_TIME_PCG_PRECON           25
#define id_BMG3_STOP_TOL                  26
#define id_BMG3_OUT_TOL                   27
#define id_BMG3_OUT_RES_L2_0              28
#define id_BMG3_OUT_RES_L2_final          29
#define id_BMG3_OUT_RHO_init              30
#define id_BMG3_OUT_RHO_last              31
#define id_BMG3_OUT_RHO_avg               32
#define id_BMG3_TIME_SETUP                33
#define id_BMG3_TIME_SETUP_FINE_STENCIL   34
#define id_BMG3_TIME_SETUP_CG_ITLI        35
#define id_BMG3_TIME_SETUP_INTERP_OI      36
#define id_BMG3_TIME_SETUP_RELAX          37
#define id_BMG3_TIME_SETUP_CG_LU          38
#define id_BMG3_TIME_SETUP_PTR_GRID       39
#define id_BMG3_TIME_SETUP_PARTS          40
#define id_BMG3_TIME_SETUP_MSG            41
#define id_BMG3_TIME_SETUP_LS             42
#define id_BMG3_TIME_SETUP_TOTAL          43
#define id_BMG3_TIME_CYCLE                44
#define id_BMG3_TIME_relax                45
#define id_BMG3_TIME_restrict             46
#define id_BMG3_TIME_interp_add           47
#define id_BMG3_TIME_SOLVE_CG             48
#define id_BMG3_TIME_SOLVE_TOTAL          49
#define id_BMG3_TIME_PCG_TOTAL            50
#define id_BMG3_TIME_PCG_PRECON           51
#define NBMG2_rPARMS                      26
#define NBMG3_rPARMS                      26
#define NBMG_rPARMS                       52

#define BMG_STENCIL_5pt                   1
#define BMG_STENCIL_9pt                   2
#define BMG_STENCIL_7pt                   1
#define BMG_STENCIL_27pt                  2

#define BMG_BCs_definite                  0
#define BMG_BCs_def_per_x                 2
#define BMG_BCs_def_per_y                 1
#define BMG_BCs_def_per_xy                3
#define BMG_BCs_indef_per_x               -2
#define BMG_BCs_indef_per_y               -1
#define BMG_BCs_indef_per_xy              -3
#define BMG_BCs_indef_nonper              -4

#define BMG_SETUP_only                    3
#define BMG_SETUP_none                    2
#define BMG_SETUP_ptrs                    4
#define BMG_SETUP_opers                   1
#define BMG_SETUP_ptrs_opers              0

#define BMG_USE_pointers                  1
#define BMG_NO_pointers                   0

#define BMG_GS_RB_point                   1
#define BMG_GS_RB_x_lines                 2
#define BMG_GS_RB_y_lines                 3
#define BMG_GS_RB_x_y_lines               4
#define BMG_GS_RB_planes_xy_yz_xz         5

#define BMG_RELAX_NONSYM                  0
#define BMG_RELAX_SYM                     1

#define BMG_DOWN                          0
#define BMG_UP                            1

/*--------------------------------                                           */
/*Initial Guess                                                              */
/*--------------------------------                                           */

#define BMG_GUESS_ZERO                    0
#define BMG_GUESS_RANDOM                  1
#define BMG_GUESS_USER                    2
#define BMG_GUESS_USER_GHOST              3

#define BMG_STOP_ABS_RES_L2               0
#define BMG_STOP_REL_RES_L2               1
#define BMG_STOP_MAX_ITERS                2

#define BMG_FMG_CYCLE                     0
#define BMG_N_CYCLE                       1
#define BMG_V_CYCLE                       1
#define BMG_W_CYCLE                       2

#define BMG_CG_ITLI_IzIyIx                1
#define BMG_CG_ITLI                       2
#define BMG_CG_USER                       3

#define BMG_CG_CONS_explicit              1
#define BMG_CG_CONS_block                 2

#define BMG_CG_ALLGATHER                  0
#define BMG_CG_GATHER_SCATTER             1

#define BMG_CG_SOLVE_LU                   0
#define BMG_CG_SOLVE_BOXMG                1

#define BMG_SYNC_INITIAL_GUESS            0
#define BMG_SYNC_INITIAL_GUESS_none       1

#define BMG_SETUP_MSG_ORIGINAL            0
#define BMG_SETUP_MSG_WITH_PERIODIC       1

#define BMG_LINE_SOLVE_COMM_TRADITIONAL   0
#define BMG_LINE_SOLVE_COMM_TUNED         1
#define iBMG2_BUG_STENCIL_FG              0
#define iBMG2_BUG_STENCIL_CG              1
#define iBMG2_BUG_STENCIL_CG1             2
#define iBMG2_BUG_RESTRICT                3
#define iBMG2_BUG_INTERP                  4
#define iBMG2_BUG_RES_INTERP              5
#define iBMG2_BUG_RES_RESTRICT            6
#define iBMG2_BUG_RES_RELAX               7
#define iBMG2_BUG_RES_CG_SOLVE            8
#define iBMG2_BUG_S                       9
#define iBMG2_BUG_MSG_GRID                10
#define iBMG2_OUT_WSPACE_SIZE             11
#define iBMG2_OUT_WSPACE_POINT            12
#define iBMG2_OUT_TIME_SETUP              13
#define iBMG2_OUT_TIME_CYCLING            14
#define iBMG2_OUT_TIME_TOTAL              15
#define iBMG2_OUT_ITERATIONS              16
#define iBMG2_OUT_STENCIL_TTY             17
#define iBMG2_OUT_RESTRICT_TTY            18
#define iBMG2_OUT_INTERP_TTY              19
#define iBMG2_WARN_ZERO_RESIDUAL          20
#define iBMG2_OUT_STOP_ERROR              21
#define iBMG3_BUG_STENCIL_FG              22
#define iBMG3_BUG_STENCIL_CG              23
#define iBMG3_BUG_STENCIL_CG1             24
#define iBMG3_BUG_RESTRICT                25
#define iBMG3_BUG_INTERP                  26
#define iBMG3_BUG_RES_INTERP              27
#define iBMG3_BUG_RES_RESTRICT            28
#define iBMG3_BUG_RES_RELAX               29
#define iBMG3_BUG_RES_CG_SOLVE            30
#define iBMG3_BUG_S                       31
#define iBMG3_BUG_MSG_GRID                32
#define iBMG3_OUT_WSPACE_SIZE             33
#define iBMG3_OUT_WSPACE_POINT            34
#define iBMG3_OUT_TIME_SETUP              35
#define iBMG3_OUT_TIME_CYCLING            36
#define iBMG3_OUT_TIME_TOTAL              37
#define iBMG3_OUT_ITERATIONS              38
#define iBMG3_OUT_STENCIL_TTY             39
#define iBMG3_OUT_RESTRICT_TTY            40
#define iBMG3_OUT_INTERP_TTY              41
#define iBMG3_WARN_ZERO_RESIDUAL          42
#define iBMG3_OUT_STOP_ERROR              43
#define iBMG_OUT_SOLUTION                 44
#define iBMG_OUT_RHS                      45
#define NBMG2_IOFLAG                      23
#define NBMG3_IOFLAG                      23
#define NBMG_IOFLAG                       46


#endif

