! ==========================================================================
! 
! 
!    "f90/f95" include file generated by $BOXMGdist/make/BMGincludes.py
! 
! 
! ******************************************************
! 
! Include file for the communication routines
! 
! version 2.0
! 
! ******************************************************
! 
! MAX_PROCS defines the maximal number of
! adjacent processors
! 
      integer MAX_PROCS
      parameter (MAX_PROCS = 27)
! 
! MAX_PATTERNS defines the maximal number of patterns
! of repeated communications
! 
      integer MAX_PATTERNS
      parameter (MAX_PATTERNS = 6)
