! ==========================================================================
! 
! 
!    "f90/f95" include file generated by $BOXMGdist/make/BMGincludes.py
! 
! 
! _____________________________________________
! 
! include file to describe the MSG functions
! 
! version 2.0
! 
! ---------------------------------------------

      real*8 MSG_timer
      integer MSG_myproc
      integer MSG_nproc
      integer MSG_VERSION
      common /MSG_GLOBAL_DATA/ MSG_VERSION
