/* Generated by Cython 0.29.34 */

#ifndef __PYX_HAVE__pyrelax
#define __PYX_HAVE__pyrelax

#include "Python.h"

#ifndef __PYX_HAVE_API__pyrelax

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C void gs_iter(int, int, int, int, double *);
__PYX_EXTERN_C double get_high_freq(int, int, double *);

#endif /* !__PYX_HAVE_API__pyrelax */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initpyrelax(void);
#else
PyMODINIT_FUNC PyInit_pyrelax(void);
#endif

#endif /* !__PYX_HAVE__pyrelax */
