name: CI

on:
  push:
    branches: main
  pull_request:
    branches: main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Unset CC and CXX
        run: |
          test -n $CC  && unset CC
          test -n $CXX && unset CXX

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install cmake mpich liblapack-dev libboost-filesystem-dev libboost-system-dev python3 clang
          sudo pip install numpy pyamg
      - name: build Cedar setup
        run: |
          mkdir build
          cd build
          cmake --debug-find -DENABLE_UNIT_TESTS=yes -DCMAKE_CXX_COMPILER=clang++ ..
      - name: make and test Cedar
        run: make && make test
